### ISSUE TITLE
A Login  problem on your project

### ISSUE THREAD

**Issue by GuessWhoIAm-MyGithub** [growvv/whu_gym#2]
1.LOGIN:  the Login url in your project can't be used for signing up because ,Since  grade 2019, the way to sign up has been change to use the WHU-offical website, and we don't have the  account_name+password infomation teh config.py need.
(url:https://cas.whu.edu.cn/authserver/loginservice=http://gym.whu.edu.cn:80/wechat/autoLoginConnector.jsp)
This website cannot be post by accountName+password because the password is encrypted by an unknown method.
Maybe the encryption is written is one .js file which I didn't notice. For this reason,the program can be run if and only if i GET my COOKIE by logging in  manually .

 2. THE SUBMIT: the result.text returned by posting the order sometimes is empty which will cause program exit while no order is accepted.

 3. TIME: the access time to the next-day field maybe starts from 18:01:50 not 18:02:50 since I manually reserve at 18:01:xx
 

And twilo seems banned to new  Chinese private users.

**Comment by GuessWhoIAm-MyGithub** [comment]
Well, after my 2 hours analysis, the new login website encrypt every useful information , the difficulty to simulate post rise up exponentially.To many simplified .js files are used for the encryption.

**Comment by growvv** [comment]
thanks
